### ISSUE TITLE
Second request within same session doesn't work

### ISSUE THREAD

**Issue by tlaguz** [alexeyzimarev/Autofac.Extras.ServiceStack#3] opened 2015-12-09 12:44 UTC
HostContext.RequestContext.Items seems to be persistent for same http sessions.

Resolve and TryResolve methods choose which container should they use based on "AutofacScope" item existence, but this item never gets removed.
This leads to an error during second request (within same http session):

```
Error trying to resolve Service 'ServiceStack.Caching.ICacheClient' from Adapter 'AutofacIocAdapter':
Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
```

This error is raised before CreateScope filter is called so I assume this is servicestack's dependency.

To solve I've changed DisposeScope method to:

```
private static void DisposeScope()
{
    if (!HostContext.RequestContext.Items.Contains("AutofacScope")) { return; }
    var scope = HostContext.RequestContext.Items["AutofacScope"] as IDisposable;
    scope?.Dispose();
    HostContext.RequestContext.Items.Remove("AutofacScope");
}
```

**Comment by alexeyzimarev** [comment] 2015-12-09 21:51
Are you sure this is not the result of adding lifecycle context to TryResolve? Can you make a sample repository to reproduce this issue?

**Comment by tlaguz** [comment] 2015-12-18 14:08
My change to DisposeScope does not fix the problem in 100%.
When exception is thrown in Resolve<T> DisposeScope is not being called.
I have fixed it by:

```
    public T Resolve<T>()
    {
        var scope = HostContext.RequestContext.Items["AutofacScope"] as ILifetimeScope;

        if (scope != null)
        {
            try
            {
                return scope.Resolve<T>();
            }
            catch (ObjectDisposedException)
            {
                HostContext.RequestContext.Items.Remove("AutofacScope");
            }
        }

        return Container.Resolve<T>();
    }

    public T TryResolve<T>()
    {
        var scope = HostContext.RequestContext.Items["AutofacScope"] as ILifetimeScope;
        T result;

        if (scope != null)
        {
            try
            {
                return scope.TryResolve(out result) ? result : default(T);
            }
            catch (ObjectDisposedException)
            {
                HostContext.RequestContext.Items.Remove("AutofacScope");
            }
        }

        return Container.TryResolve(out result) ? result : default(T);
    }
```

I have sample repository on my todo list, but I don't have enough time to do this now (end of the year). Sorry

**Comment by alexeyzimarev** [comment] 2015-12-18 14:38
We are starting to use the package more actively and so far have not seen this but we don't use cache yet. We will see how that goes. If you make a sample repo or I will encounter the issue myself, I will fix is asap.

**Comment by tlaguz** [comment] 2015-12-18 15:18
Can you confirm that RequestContext.Items contents are shared between multiple requests from the same host?

When I send a lot of requests (in parallel) my lifetimescope gets disposed. Sending one request works.

Definition of Items from RequestContext:

```
    // Summary:
    //     Gets a list of items for this request.
    //
    // Remarks:
    //     This list will be cleared on every request and is specific to the original thread
    //     that is handling the request. If a handler uses additional threads, this data
    //     will not be available on those threads.
```

Why I see previous lifetimescope in CreateScope of next request?
This happens even on code from master (without my changes).

BTW:

```
 appHost.GlobalMessageRequestFilters.Add((req, resp, dto) => CreateScope(container));
 appHost.GlobalMessageRequestFilters.Add((req, resp, dto) => DisposeScope());
```

Shouldn't dispose be registered to ...ResponseFilters?

**Comment by tlaguz** [comment] 2015-12-18 15:26
![servicestackrequest](https://cloud.githubusercontent.com/assets/6138529/11900116/fbdcdd78-a5a3-11e5-8d15-29eac8dc4829.png)

As you can see on thread window, every CreateScope is called from different thread, but Items are not empty.

**Comment by mythz** [comment] 2015-12-18 16:15
@tlaguz can you put together a stand-alone program in a gist we can debug locally to see this issue?

**Comment by alexeyzimarev** [comment] 2015-12-18 17:26
Yes, it would be nice to see some more code. I am looking at ServiceStack code now and I see, for example, this: https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Service.cs#L180
Since services have "per request"scope by default, this code means that RequestContext.Instance should represent current request and when the service is disposed, all instantiated IDisposable's are also disposed. Maybe I need to use RequestContext.Instance.TrackDisposable. But if I would have some sample code and some way to reproduce it, it would really help.

Concerning the message filters - you're right. I will fix that one.

**Comment by tlaguz** [comment] 2015-12-18 23:05
[SSProblemExtracted.zip](https://github.com/alexeyzimarev/Autofac.Extras.ServiceStack/files/67284/SSProblemExtracted.zip)

Open http://localhost:8888/hello/world address and hold F5. In console output you will see that Items has AutofacScope item before creating it.

**Comment by mythz** [comment] 2015-12-20 23:41
@tlaguz You can workaround this issue by switching to store Request Context items in Thread Static dictionary, i.e. by setting:

``` csharp
RequestContext.UseThreadStatic = true;
```

Otherwise you can just upgrade to the latest v4.0.50 packages on NuGet which doesn't look like it has the issue.

**Comment by tlaguz** [comment] 2015-12-22 11:43
@mythz I can upgrade my solution to latest packages, but can you assure me this is known bug?
I have permissions saved in DI and I cannot allow it to mix perms among sessions.

**Comment by alexeyzimarev** [comment] 2016-02-03 14:17
Since there is no reproduction of the issue available, I am closing it.

**Closed as completed by alexeyzimarev** 2016-02-03 14:17 UTC
